
const Type = {
    USER_REGISTRATION : 'USER_REGISTRATION',
    USER_REGISTRATION_ERROR : 'USER_REGISTRATION_ERROR',
    USER_LOGIN : 'USER_LOGIN',
    USER_LOGIN_ERROR : 'USER_LOGIN_ERROR'

}

export default Type;